
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:32768/spring-forum
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.gmail.com
    username: miage.sid.2018@gmail.com
    password: jesuissid
    port: 587
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      starttls.required: true
  profiles:
    active: dev
  activemq:
    packages:
      trust-all: true
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: 129928913750-gbr8vns4217rdgrg77jb09hoqd5qtas6.apps.googleusercontent.com
      client-secret: 4rMi3WTkJTBbYSUU8sUIUAqd
      access-token-uri: https://accounts.google.com/o/oauth2/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/auth
      client-authentication-scheme: form
      scope:
          - openid
          - email
          - profile
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: false
    sso:
      login-path: /login/google


