spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-forum
    username: postgres
    password: postgres
  session:
    store-type: jdbc
  jpa:
    hibernate:
      ddl-auto: create

security:
  oauth2:
    client:
      client-id: 129928913750-gbr8vns4217rdgrg77jb09hoqd5qtas6.apps.googleusercontent.com
      client-secret: 4rMi3WTkJTBbYSUU8sUIUAqd
      access-token-uri: https://accounts.google.com/o/oauth2/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/auth
      token-name: oauth_token
      authentication-scheme: query
      client-authentication-scheme: form
      scope: profile
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      prefer-token-info: true
    sso:
      login-path: /login/google


